# The basic colors
foreground              #c9c2d7
background              #1a1a1e
selection_foreground    #1a1a1e
selection_background    #cdbaf2

# Cursor colors
cursor                  #e6ac96
cursor_text_color       #1a1a1e

# URL underline color when hovering with mouse
url_color               #cdbaf2

# Kitty window border colors
active_border_color     #cdbaf2
inactive_border_color   #574e5f
bell_border_color       #bd6870

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1a1a1e
active_tab_background   #cdbaf2
inactive_tab_foreground #c9c2d7
inactive_tab_background #303066
tab_bar_background      #1a1a1e

# Colors for marks (marked text in the terminal)
mark1_foreground #1a1a1e
mark1_background #303066
mark2_foreground #1a1a1e
mark2_background #cdbaf2
mark3_foreground #1a1a1e
mark3_background #e6ac96

# The 16 terminal colors

# black / dark
color0 #1a1a1e
color8 #574e5f

# red
color1 #bd6870
color9 #bd6870

# green (substituted with muted brown/red for harmony)
color2  #956c69
color10 #956c69

# yellow (substituted with peach)
color3  #e6ac96
color11 #e6ac96

# blue
color4  #303066
color12 #303066

# magenta / purple
color5  #cdbaf2
color13 #cdbaf2

# cyan (substituted with muted purple)
color6  #9788a5
color14 #9788a5

# white / light text
color7  #c9c2d7
color15 #c9c2d7