include                 theme.conf
font_family             JetBrainsMono Nerd Font Mono
font_size               16.0
window_padding_width    1
italic_font             auto
bold_font               auto
bold_italic_font        auto
background_opacity 0.99
background_blur 15
dynamic_background_opacity yes
copy_on_select          yes
scrollbar               never
confirm_os_window_close 0
cursor_trail            1
strip_trailing_spaces smart
open_url_with default
detect_urls yes
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval -1
