foreground              #f0dee0
background              #191112
selection_foreground    #561d2a
selection_background    #713340
cursor                  #ffb2be
cursor_text_color       #561d2a
url_color               #ffb2be
active_border_color     #ffb2be
inactive_border_color   #524345
bell_border_color       #ffb4ab
wayland_titlebar_color system
macos_titlebar_color system
active_tab_foreground   #561d2a
active_tab_background   #713340
inactive_tab_foreground #f0dee0
inactive_tab_background #261d1f
tab_bar_background      #191112
mark1_foreground #f0dee0
mark1_background #261d1f
mark2_foreground #561d2a
mark2_background #713340
mark3_foreground #ffddbb
mark3_background #5f401c
color0 #261d1f
color8 #9f8c8e
color1 #ffb4ab
color9 #ffb4ab
color2  #e4bdc2
color10 #ffd9de
color3  #ebbe90
color11 #ffddbb
color4  #ffb2be
color12 #ffd9de
color5  #ebbe90
color13 #5f401c
color6  #e4bdc2
color14 #5c3f44
color7  #d6c2c4
color15 #f0dee0
