# Base colors
foreground              #e2e2e2
background              #131313
selection_foreground    #5f1413
selection_background    #7e2a27
cursor                  #ffb3ad
cursor_text_color       #5f1413
url_color               #ffb3ad

# Borders
active_border_color     #ffb3ad
inactive_border_color   #474747
bell_border_color       #ffb4ab
wayland_titlebar_color system
macos_titlebar_color system

# Tabs
active_tab_foreground   #5f1413
active_tab_background   #7e2a27
inactive_tab_foreground #e2e2e2
inactive_tab_background #1f1f1f
tab_bar_background      #131313

# Marks
mark1_foreground #e2e2e2
mark1_background #1f1f1f
mark2_foreground #5f1413
mark2_background #7e2a27
mark3_foreground #ffdea6
mark3_background #584319

# ANSI colors (using full palette)
color0  #1f1f1f
color1  #ffb4ab
color2  #e7bdb9
color3  #e1c28c
color4  #ffb3ad
color5  #584319
color6  #5d3f3d
color7  #c6c6c6
color8  #919191
color9  #93000a
color10 #ffdad6
color11 #ffdea6
color12 #ffdad6
color13 #ffdea6
color14 #ffdad6
color15 #e2e2e2
