foreground              #eadfe6
background              #171217
selection_foreground    #171217
selection_background    #eab5ee
cursor                  #eab5ee
cursor_text_color       #171217
url_color               #eab5ee

active_border_color     #eab5ee
inactive_border_color   #4d444c
bell_border_color       #ffb4ab

active_tab_foreground   #171217
active_tab_background   #eab5ee
inactive_tab_foreground #eadfe6
inactive_tab_background #231e23
tab_bar_background      #171217

mark1_foreground #eadfe6
mark1_background #231e23
mark2_foreground #171217
mark2_background #eab5ee
mark3_foreground #eadfe6
mark3_background #d7bfd5

color0  #1e1a1e
color1  #de3730
color2  #84468e
color3  #ba837b
color4  #bb78c5
color5  #857185
color6  #9e6a63
color7  #e9e0e4
color8  #7b7579
color9  #ffb4ab
color10 #bb78c5
color11 #f5b8af
color12 #f5adfe
color13 #bba4ba
color14 #ba837b
color15 #fffbff
