[config]
version_check = false

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

[templates.niri]
input_path='~/.config/matugen/templates/niri.kdl'
output_path='~/.config/niri/colors.kdl'

[templates.mpv]
input_path = '~/.config/matugen/templates/mpv/mpv.conf'
output_path = '~/.config/mpv/script-opts/niri_caelestia.conf'

[templates.btop]
input_path = '~/.config/matugen/templates/btop/btop.theme'
output_path = '~/.config/btop/themes/niri_caelestia.theme'
# Add this block to ~/.config/matugen/config.toml
# It hooks into your existing caelestia theming pipeline

[templates.niri-caelestia-sddm]
input_path  = '~/.config/niri-caelestia-sddm/SddmColors.qml'
output_path = '~/.config/niri-caelestia-sddm/Colors.qml'
post_hook   = 'sudo ~/.config/niri-caelestia-sddm/sddm-theme-apply.sh &'

[templates.obsidian]
input_path = '/home/sarok/.config/matugen/templates/obsidian-template.css'
output_path = '/home/sarok/Documents/Story/.obsidian/snippets/matugen-colors.css'

[templates.waybar]
input_path = '/home/sarok/.config/matugen/templates/waybar.css'
output_path = '/home/sarok/.config/waybar/style.css'
post_hook = 'pkill waybar; waybar &'
