# Base colors
foreground            {{colors.on_surface.default.color}}
background            {{colors.surface.default.color}}
selection_foreground  {{colors.on_primary.default.color}}
selection_background  {{colors.primary_container.default.color}}
cursor                {{colors.primary.default.color}}
cursor_text_color     {{colors.on_primary.default.color}}
url_color             {{colors.primary.default.color}}

# Borders
active_border_color     {{colors.primary.default.color}}
inactive_border_color   {{colors.outline_variant.default.color}}
bell_border_color       {{colors.error.default.color}}
wayland_titlebar_color system
macos_titlebar_color system

# Tabs
active_tab_foreground   {{colors.on_primary.default.color}}
active_tab_background   {{colors.primary_container.default.color}}
inactive_tab_foreground {{colors.on_surface.default.color}}
inactive_tab_background {{colors.surface_container.default.color}}
tab_bar_background      {{colors.surface.default.color}}

# Marks
mark1_foreground {{colors.on_surface.default.color}}
mark1_background {{colors.surface_container.default.color}}
mark2_foreground {{colors.on_primary.default.color}}
mark2_background {{colors.primary_container.default.color}}
mark3_foreground {{colors.tertiary_fixed.default.color}}
mark3_background {{colors.tertiary_container.default.color}}

# ANSI 0-7 (basic)
color0 {{colors.surface_container.default.color}}
color1 {{colors.error.default.color}}
color2 {{colors.secondary.default.color}}
color3 {{colors.tertiary.default.color}}
color4 {{colors.primary.default.color}}
color5 {{colors.tertiary_container.default.color}}
color6 {{colors.secondary_container.default.color}}
color7 {{colors.on_surface_variant.default.color}}

# ANSI 8-15 (bright)
color8  {{colors.outline.default.color}}
color9  {{colors.error_container.default.color}}
color10 {{colors.secondary_fixed.default.color}}
color11 {{colors.tertiary_fixed.default.color}}
color12 {{colors.primary_fixed.default.color}}
color13 {{colors.tertiary_fixed_dim.default.color}}
color14 {{colors.secondary_fixed_dim.default.color}}
color15 {{colors.on_surface.default.color}}