[flavor]
name = "matugen"
[fg] normal = "#f0dee0"; bold = "#f0dee0"; dim = "#d6c2c4"
[bg] normal = "#191112"; bold = "#261d1f"
[border] normal = "#9f8c8e"; active = "#ffb2be"
[selection] fg = "#561d2a"; bg = "#ffb2be"
[scrollbar] fg = "#ffb2be"; bg = "#261d1f"
[separator] fg = "#524345"
[cursor] fg = "#561d2a"; bg = "#ffb2be"
[link] fg = "#ffb2be"
[link_hint] fg = "#e4bdc2"
[marker] fg = "#ebbe90"
[flag] fg = "#ffb4ab"
[info] fg = "#f0dee0"; bg = "#261d1f"
[warning] fg = "#ffddbb"; bg = "#5f401c"
[error] fg = "#ffb4ab"; bg = "#93000a"
[spinner] fg = "#ffb2be"
[status] loading = "#ffb2be"
[title] fg = "#f0dee0"; bg = "#261d1f"
[extra] prompt = "#ffb2be"
[input] fg = "#f0dee0"; bg = "#261d1f"
[tab_num] fg = "#f0dee0"; bg = "#312829"
[tab_active] fg = "#561d2a"; bg = "#ffb2be"
[tab_sep] fg = "#9f8c8e"
