[flavor]
name = "matugen"

[fg]
normal = "#e2e2e2"
bold = "#b2c5ff"
dim = "#c6c6c6"

[bg]
normal = "#131313"
bold = "#1f1f1f"

[border]
normal = "#919191"
active = "#b2c5ff"

[selection]
fg = "#002c72"
bg = "#b2c5ff"

[scrollbar]
fg = "#b2c5ff"
bg = "#1f1f1f"

[separator]
fg = "#474747"

[cursor]
fg = "#002c72"
bg = "#b2c5ff"

[link]
fg = "#b2c5ff"
hover = "#b2c5ff"

[link_hint]
fg = "#c0c6dd"

[marker]
fg = "#e1bbdd"

[flag]
fg = "#ffb4ab"

[info]
fg = "#e2e2e2"
bg = "#1f1f1f"

[warning]
fg = "#fed7f9"
bg = "#5a3d59"

[error]
fg = "#ffb4ab"
bg = "#93000a"

[spinner]
fg = "#b2c5ff"

[status]
loading = "#b2c5ff"

[title]
fg = "#e2e2e2"
bg = "#1f1f1f"

[extra]
prompt = "#b2c5ff"
success = "#c0c6dd"
warning = "#e1bbdd"

[input]
fg = "#e2e2e2"
bg = "#1f1f1f"

[tab_num]
fg = "#e2e2e2"
bg = "#2a2a2a"

[tab_active]
fg = "#002c72"
bg = "#b2c5ff"

[tab_sep]
fg = "#919191"
