[flavor]
name = "matugen"

[fg]
normal = "#e2e2e2"
bold = "#ffb3ac"
dim = "#c6c6c6"

[bg]
normal = "#131313"
bold = "#1f1f1f"

[border]
normal = "#919191"
active = "#ffb3ac"

[selection]
fg = "#5f1413"
bg = "#ffb3ac"

[scrollbar]
fg = "#ffb3ac"
bg = "#1f1f1f"

[separator]
fg = "#474747"

[cursor]
fg = "#5f1413"
bg = "#ffb3ac"

[link]
fg = "#ffb3ac"
hover = "#ffb3ac"

[link_hint]
fg = "#e7bdb8"

[marker]
fg = "#e1c38c"

[flag]
fg = "#ffb4ab"

[info]
fg = "#e2e2e2"
bg = "#1f1f1f"

[warning]
fg = "#fedea6"
bg = "#584419"

[error]
fg = "#ffb4ab"
bg = "#93000a"

[spinner]
fg = "#ffb3ac"

[status]
loading = "#ffb3ac"

[title]
fg = "#e2e2e2"
bg = "#1f1f1f"

[extra]
prompt = "#ffb3ac"
success = "#e7bdb8"
warning = "#e1c38c"

[input]
fg = "#e2e2e2"
bg = "#1f1f1f"

[tab_num]
fg = "#e2e2e2"
bg = "#2a2a2a"

[tab_active]
fg = "#5f1413"
bg = "#ffb3ac"

[tab_sep]
fg = "#919191"
